config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'grand_parents#index'

  resources :grand_parents do
    resources :bookings, only: [:new, :create, :reservation, :edit, :update]
  end

  resources :bookings, only: [:index, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :grand_parent
  validates :date_start, :date_end, presence: true
end

app/models/grand_parent.rb
class GrandParent < ApplicationRecord
   include PgSearch::Model
  pg_search_scope :search_by_first_name_city_hobby,
    against: [ :city, :hobby, :first_name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  belongs_to :user
  validates :first_name, :last_name, :price, :city, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :bookings
  has_many :booked_grand_parents, through: :bookings, source: :grand_parent
  has_many :grand_parents, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
   before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user: current_user)
  end

  def create
    @grand_parent = GrandParent.find(params[:grand_parent_id])
    @booking = Booking.new(booking_params)
    @booking.grand_parent = @grand_parent
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render 'grand_parents/show'
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to grand_parent_path(@booking.grand_parent_id)
    else
      render 'bookings'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to grand_parent_path(@booking.grand_parent)
  end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end, :review)
  end
end

app/controllers/grand_parents_controller.rb
class GrandParentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index , :show]
  before_action :set_grand_parent, only: [:show, :edit, :update, :destroy]

  def index
    @query = params[:query]
    if @query.present?
      @grand_parents = GrandParent.search_by_first_name_city_hobby(@query).order(created_at: :desc)
    else
      @grand_parents = GrandParent.geocoded.order(created_at: :desc) # returns flats with coordinates
    end
    @markers = @grand_parents.map do |grand_parent|
      {
        lat: grand_parent.latitude,
        lng: grand_parent.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { grand_parent: grand_parent })
      }
    end
  end

  def show
    @booking = Booking.new
    @grand_parent = GrandParent.find(params[:id])
    @bookings       = @grand_parent.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.date_start,
        to:   booking.date_end
      }
    end
  end

  def new
    @grand_parent = GrandParent.new
  end

  def create
    @grand_parent = GrandParent.new(grand_parent_params)
    @grand_parent.user = current_user

    if @grand_parent.save
      redirect_to grand_parent_path(@grand_parent)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @grand_parent.update(grand_parent_params)
    if @grand_parent.save
      redirect_to grand_parent_path(@grand_parent)
    else
      render :edit
    end
  end

  def destroy
    @grand_parent.destroy
    redirect_to grand_parents_path
  end

  private

  def set_grand_parent
    @grand_parent = GrandParent.find(params[:id])
  end

  def grand_parent_params
    params.require(:grand_parent).permit(:first_name, :last_name, :description, :price, :age, :hobby, :city, :photos)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<div class="black">
  <div id="booking-form-div" data-bookings="<%= @bookings_dates.to_json %>"></div>
    <div class="form-wrapper">
      <%= simple_form_for [grand_parent, booking] do |f| %>
      <%= f.input :date_start, label: "Sélectionnez vos dates de réservation", as: :string, required: false, input_html: { id: "range_start", class: "d-none"} %>
      <%= f.input :date_end, label: false, as: :string, required: false, input_html: { id: "range_end", class: "d-none" } %>
      <div id="votre_resa"></div>
      <div class="d-flex m-auto">
        <%= f.button :submit, "Book", class: "btn btn-primary m-auto our-button" %>
      </div>
      <% end %>
    </div>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h2>Mes Réservations</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <% @bookings.each do |booking| %>
      <div class="d-flex justify-content-between mt-5" style="width: 100%;">
      <div class="card-booking col-6">
        <% if booking.grand_parent.photos.attached? %>
        <% booking.grand_parent.photos.each do |photo| %>
        <%= cl_image_tag photo.key %>
        <% end %>
        <% else %>
        <%= image_tag "https://image.freepik.com/vecteurs-libre/conception-grands-parents_25030-23616.jpg" %>
        <% end %>
        <div class="card-booking-infos">
          <h3>Votre réservation avec <strong><%= booking.grand_parent.first_name %></strong></h3>
          <p>Date de début le <strong><%= booking.date_start.strftime("%m/%d/%Y")  %></strong></p>
          <p>Date de fin le <strong><%= booking.date_start.strftime("%m/%d/%Y") %></strong></p>
        </div>
      </div>

        <div class="form-wrapper col-6">
          <%= simple_form_for [ booking.grand_parent, booking ] do |f| %>
          <%= f.input :review %>
          <%= f.button :submit, "Envoyez votre avis", class: "btn btn-primary" %>
          <% end %>
        </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/grand_parents/_form_search.html.erb
<div class= "form-inline">
   <%= form_tag grand_parents_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Trouve ton vieux"
  %>
  <%= submit_tag "Search", class: "btn btn-primary our-button" %>
<% end %>
</div>

app/views/grand_parents/_info_window.html.erb
<h2><%= grand_parent.first_name %></h2>
<p><%= grand_parent.city %></p>

app/views/grand_parents/edit.html.erb
<!-- <div class="container mt-2 rounded" style= "background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1490349708435-19d432984978?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1487&q=80);"> -->
<div class="box">
  <div class="add-image">
    <h1 class="add-title">Modifie Ton Annonce</h1>
  </div>
  <div class="add-form container col-sm-8 col-lg-4">
    <%= simple_form_for (@grand_parent) do |f| %>
      <%= f.input :first_name, label: "Prénom"%>
      <%= f.input :last_name, label: "Nom" %>
      <%= f.input :age, label:"Age" %>
      <%= f.input :description %>
      <%= f.input :hobby, label: "Loisirs" %>
      <%= f.input :city, label: "Adresse" %>
      <%= f.input :price, label: "Prix" %>
      <div class="new-form-buttons">
        <label class="btn btn-outline-info" style="style: width: 100%">
          Ajouter une photo <em> (10.5 Mb max.)</em>
          <span style="display:none;">
            <%= f.input :photo, as: :file, name: 'Photo' %>
          </span>
        </label>
      </div>
      <%= f.submit "Modifier", class: "btn btn-primary submit-new"  %>
    <% end %>
  </div>
</div>

app/views/grand_parents/index.html.erb
<%= render 'shared/banner' %>
<div class="home-container">

  <div class="container mt-5">
    <div class="row">
      <% @grand_parents.each do |gp| %>
        <div class="col-xs-4 col-md-4">
          <div class="card-gp m-3">
            <% if gp.photos.attached? %>
              <% gp.photos.each do |photo| %>
                <%= cl_image_tag photo.key %>
              <% end %>
            <% else %>
              <%= image_tag "https://image.freepik.com/vecteurs-libre/conception-grands-parents_25030-23616.jpg" %>
            <% end %>

            <div class="card-gp-infos">
              <%= link_to grand_parent_path(gp) do  %>
                <h2><%= gp.first_name %> <%= gp.last_name %></h2>
                <p><%= gp.description %></p>
                <h2 class="card-gp-pricing"><%= gp.price %>€</h2>

                <%= cl_image_tag gp.user.avatar.key, class: "card-gp-user avatar-bordered" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div id="map"
   style="width: 50%;
   height: 90vh;"
   data-markers="<%= @markers.to_json %>"
   data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/grand_parents/new.html.erb
<!-- <div class="container mt-2 rounded" style= "background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1490349708435-19d432984978?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1487&q=80);"> -->
<div class="box">
  <div class="add-image">
    <h1 class="add-title">Ajoute Ton Grand Parent</h1>
    </div>
  <div class="add-form container col-sm-8 col-lg-4">
      <%= simple_form_for (@grand_parent) do |f| %>
        <div class="row">
          <div class="col">
            <%= f.input :first_name, label: false, placeholder: "Prénom"%>
          </div>
          <div class="col">
            <%= f.input :last_name, label: false, placeholder: "Nom" %>
          </div>
        </div>

        <div class="row">
          <div class="col">
            <%= f.input :age, label: false, placeholder: "Age" %>
          </div>
          <div class="col">
            <%= f.input :hobby, label: false, placeholder: "Loisirs" %>
          </div>
          <div class="col">
            <%= f.input :price, label: false, placeholder: "Prix" %>
          </div>
        </div>

        <%= f.input :city, label: false, placeholder: "Adresse" %>
        <%= f.input :description, label: false, placeholder: "Description"  %>
          <div class="new-form-buttons">
          <label class="btn btn-outline-info" style="style: width: 100%">
            Ajouter une photo <em> (10.5 Mb max.)</em>
            <span style="display:none;">
              <%= f.input :photo, as: :file, name: 'Photo' %>
            </span>
          </label>
          <%= f.submit "Proposer", class: "btn btn-primary submit-new our-button"  %>
        </div>
      <% end %>
  </div>
</div>

app/views/grand_parents/show.html.erb
<div class="show-gp">
  <% if @grand_parent.photos.attached? %>
    <% @grand_parent.photos.each do |photo| %>
      <div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path photo.key, :width=>300, :height=>200, :crop=>"fill"  , :gravity=>"face" %>);">
        <% end %>
        <% else %>
        <div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path "logo.svg" %>);">
        <% end %>
          <%= @grand_parent.first_name %>
      </div>
    </div>

  <div class="container">
    <div class="d-flex justify-content-around w-100">
      <div class="w-50 p-4">
        <div class="card-product-infos">
          <div style="height: 130px; padding: 15px;">
            <h4><%= @grand_parent.description %></h4>
          </div>
          <div>
            <div class="tags-infos">
              <p><i class="fas fa-cat"></i> <%= @grand_parent.hobby %></p>
            </div>
            <div class="tags-infos">
              <p><i class="fas fa-map-marker-alt"></i> <%= @grand_parent.city %></p>
            </div>
            <div class="tags-infos">
              <p><i class="fas fa-birthday-cake"></i> <%= @grand_parent.age %> ans</p>
            </div>
            <div class="tags-infos">
              <p><i class="fas fa-euro-sign"></i> <span id="price_gp"><%= @grand_parent.price %></span> euros</p>
            </div>

          </div>
        </div>

        <% if @bookings.present? %>
        <h2>Les avis</h2>
        <% end %>
        <% @bookings.each do |booking| %>
        <div class="card-product-review">
        <p><%= booking.user.full_name %></p>
        <p><%= booking.review %></p>
        </div>
        <% end %>
      </div>

      <div class="w-50 p-4">
      <%= render "bookings/new", grand_parent: @grand_parent, booking: @booking %>
      </div>
    </div>

    <div class="container d-flex justify-content-center">
     <p>
      <%= link_to 'Supprimer', grand_parent_path(@grand_parent), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-flat our-button' %>
      <%= link_to 'Modifier', edit_grand_parent_path(@grand_parent), class: 'btn btn-flat our-button' %>
     </p>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Mamys&Papys</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.7.0/mapbox-gl.css' rel='stylesheet' />
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%#= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_banner.html.erb
<div class="row">
  <div class="col">
    <div class="banner">
      <%= render 'shared/carousel' %>
      <div class="home-tagline ">
        <h1>Mamys & Papys !</h1>
        <p>Découvrez nos supers grands-parents qui se feront une joie de vous recevoir chez eux. Un moment idéal de partage et de convivialté.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active w-100 h-640" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1490349708435-19d432984978?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1487&q=80')">
      <!-- <img class="d-block w-100" src="https://images.unsplash.com/photo-1490349708435-19d432984978?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1487&q=80" alt="First slide"> -->
    </div>
    <div class="carousel-item w-100 h-640" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://i.skyrock.net/1391/83881391/pics/3099348351_1_3_S1M5Jj04.jpg')">
      <!-- <img class="d-block w-100" src="https://static.wixstatic.com/media/00fb686fa41f676a938dd5563eceadba.jpg/v1/fill/w_470,h_308/00fb686fa41f676a938dd5563eceadba.jpg" alt="Second slide"> -->
    </div>
    <div class="carousel-item w-100 h-640" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://static.wixstatic.com/media/00fb686fa41f676a938dd5563eceadba.jpg/v1/fill/w_470,h_308/00fb686fa41f676a938dd5563eceadba.jpg')">
      <!-- <img class="d-block w-100" src="https://i.skyrock.net/1391/83881391/pics/3099348351_1_3_S1M5Jj04.jpg" alt="Third slide"> -->
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.santiane.fr/mutuelle-sante/guides/prix-remboursement-dentier"><i class="fas fa-teeth-open"></i></a>
    <a href="https://www.bastideleconfortmedical.com/materiel-medical/mobilite-transfert/cannes-et-accessoires.html"><i class="fas fa-candy-cane"></i></a>
    <a href="https://www.stannah.fr/"><i class="fas fa-wheelchair"></i></a>

  </div>
  <div class="footer-copyright">
    This Website is made with <i class="fas fa-heart"></i>
    <%= image_tag("Ashley.jpg", class: "avatar") %>
    <%= image_tag("Virginia.jpg", class: "avatar") %>
    <%= image_tag("Pamela.jpg", class: "avatar") %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "logo.svg", class: 'logo' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%# if params[:controller] == "grand_parents" && params[:action] == "index" %>
        <%= render "grand_parents/form_search" %>
      <%# end %>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Mes locations", bookings_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Proposer des grands-parents", new_grand_parent_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "https://image.flaticon.com/icons/svg/1246/1246351.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Mon compte", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to  new_user_registration_path, class: "nav-link" do %>
        <i class="fas fa-user-plus"></i> Inscription
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_session_path, class: "nav-link" do %>
        <i class="fas fa-sign-in-alt"></i> Connexion
        <% end %>
      </li>
      <% end %>
    </ul>
  </div>
</div>